package com.cleanroute.api;
import org.springframework.dao.DataIntegrityViolationException; import org.springframework.http.*; import org.springframework.http.converter.HttpMessageNotReadableException; import org.springframework.web.bind.MissingServletRequestParameterException; import org.springframework.web.method.annotation.MethodArgumentTypeMismatchException; import org.springframework.web.bind.MethodArgumentNotValidException; import org.springframework.web.bind.annotation.*; import org.springframework.web.server.ResponseStatusException; import java.util.*;
@RestControllerAdvice public class ApiExceptionHandler {
 @ExceptionHandler(MethodArgumentNotValidException.class) ResponseEntity<?> validation(MethodArgumentNotValidException ex){var errors=new LinkedHashMap<String,String>();ex.getBindingResult().getFieldErrors().forEach(e->errors.putIfAbsent(e.getField(),e.getDefaultMessage()));return ResponseEntity.badRequest().body(Map.of("error","validation_failed","message","Request validation failed","details",errors));}
 @ExceptionHandler({HttpMessageNotReadableException.class,MissingServletRequestParameterException.class,MethodArgumentTypeMismatchException.class,jakarta.validation.ConstraintViolationException.class}) ResponseEntity<?> malformed(Exception ex){return ResponseEntity.badRequest().body(Map.of("error","invalid_request","message","Request contains malformed or unsupported values"));}
 @ExceptionHandler(ResponseStatusException.class) ResponseEntity<?> status(ResponseStatusException ex){return ResponseEntity.status(ex.getStatusCode()).body(Map.of("error",ex.getStatusCode().toString().toLowerCase().replace(" ","_"),"message",ex.getReason()==null?"Request failed":ex.getReason()));}
 @ExceptionHandler(DataIntegrityViolationException.class) ResponseEntity<?> conflict(DataIntegrityViolationException ex){return ResponseEntity.status(409).body(Map.of("error","conflict","message","A record with these details already exists"));}
 @ExceptionHandler(Exception.class) ResponseEntity<?> unexpected(Exception ex){return ResponseEntity.status(500).body(Map.of("error","internal_error","message","An unexpected error occurred"));}
}
