package com.cleanroute.api;
import com.cleanroute.domain.*; import com.cleanroute.repository.SavedRouteRepository; import jakarta.validation.Valid; import jakarta.validation.constraints.*; import org.springframework.security.core.Authentication; import org.springframework.web.bind.annotation.*; import org.springframework.web.server.ResponseStatusException; import org.springframework.http.HttpStatus; import java.time.Instant; import java.util.*;
@RestController @RequestMapping("/api/routes") public class SavedRouteController {
 private final SavedRouteRepository routes; public SavedRouteController(SavedRouteRepository r){routes=r;}
 public record RouteRequest(@NotBlank @Size(max=200) String originName,@DecimalMin("-90.0") @DecimalMax("90.0") double originLatitude,@DecimalMin("-180.0") @DecimalMax("180.0") double originLongitude,@NotBlank @Size(max=200) String destinationName,@DecimalMin("-90.0") @DecimalMax("90.0") double destinationLatitude,@DecimalMin("-180.0") @DecimalMax("180.0") double destinationLongitude,@Size(max=100000) String geometryPolyline,@NotNull TravelMode travelMode,@NotNull RoutePreference routePreference,@DecimalMin("0.0") @DecimalMax("100.0") Double pollutionScore,@Min(0) Integer estimatedTravelTimeSeconds,@DecimalMin("0.0") Double distanceMeters){}
 public record RouteResponse(String id,String originName,double originLatitude,double originLongitude,String destinationName,double destinationLatitude,double destinationLongitude,String geometryPolyline,TravelMode travelMode,RoutePreference routePreference,Double pollutionScore,Integer estimatedTravelTimeSeconds,Double distanceMeters,Instant createdAt){}
 @PostMapping("/save") public RouteResponse save(Authentication a,@Valid @RequestBody RouteRequest r){var route=new SavedRoute(id(a),r.originName().trim(),r.originLatitude(),r.originLongitude(),r.destinationName().trim(),r.destinationLatitude(),r.destinationLongitude(),r.geometryPolyline(),r.travelMode(),r.routePreference(),r.pollutionScore(),r.estimatedTravelTimeSeconds(),r.distanceMeters());return view(routes.save(route));}
 @GetMapping("/saved") public List<RouteResponse> list(Authentication a){return routes.findAllByUserIdOrderByCreatedAtDesc(id(a)).stream().map(this::view).toList();}
 @DeleteMapping("/saved/{id}") @ResponseStatus(HttpStatus.NO_CONTENT) public void delete(Authentication a,@PathVariable UUID id){var r=routes.findByIdAndUserId(id,id(a)).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Saved route not found"));routes.delete(r);}
 private UUID id(Authentication a){return (UUID)a.getPrincipal();} private RouteResponse view(SavedRoute r){return new RouteResponse(r.getId().toString(),r.getOriginName(),r.getOriginLatitude(),r.getOriginLongitude(),r.getDestinationName(),r.getDestinationLatitude(),r.getDestinationLongitude(),r.getGeometryPolyline(),r.getTravelMode(),r.getRoutePreference(),r.getPollutionScore(),r.getEstimatedTravelTimeSeconds(),r.getDistanceMeters(),r.getCreatedAt());}
}
